name: PHPUnit Tests via Composer

on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Force PHP 7.4
        uses: nanasess/setup-php@master
        with:
          php-version: '7.4'
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Require php-cs-fixer
        run: composer require "friendsofphp/php-cs-fixer:2.18.2" --dev --prefer-dist --no-progress
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Check composer.json
        run: composer normalize --dry-run
      - name: Unit tests
        run: |
          mkdir --parents ./src ./tests
          ./vendor/bin/phpunit --no-coverage --colors=never
      - name: Psalm
        run: |
          ./vendor/bin/psalm --monochrome --no-progress --stats --show-info=false
      - name: phpstan
        run: |
          ./vendor/bin/phpstan --no-interaction --no-ansi analyse
      - name: Mess Detector
        run: |
          ./vendor/bin/phpmd src,tests json naming codesize design
      - name: php-cs-fixer
        run: |
          ./vendor/bin/php-cs-fixer fix -v --config=.php_cs.dist --using-cache=no --dry-run
